//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exp2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arcade_alternative {
            get {
                object obj = ResourceManager.GetObject("arcade_alternative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ArcadeAlternate {
            get {
                object obj = ResourceManager.GetObject("ArcadeAlternate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_map_arcade_alternative {
            get {
                object obj = ResourceManager.GetObject("font_map_arcade_alternative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_map_unicode_arcade_alternative {
            get {
                object obj = ResourceManager.GetObject("font_map_unicode_arcade_alternative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainMenu {
            get {
                object obj = ResourceManager.GetObject("MainMenu", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This font was downloaded from
        ///
        ///http://www.myfonts.me
        ///
        ///Thank you for download!!!.
        /// </summary>
        internal static string myfonts_me {
            get {
                return ResourceManager.GetString("myfonts_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to les Escaldes
        ///Andorra la Vella
        ///Umm al Qaywayn
        ///Ras al-Khaimah
        ///Khawr Fakkān
        ///Dubai
        ///Dibba Al-Fujairah
        ///Dibba Al-Hisn
        ///Sharjah
        ///Ar Ruways
        ///Al Fujayrah
        ///Al Ain
        ///Ajman
        ///Adh Dhayd
        ///Abu Dhabi
        ///Zaranj
        ///Taloqan
        ///Shīnḏanḏ
        ///Shibirghān
        ///Shahrak
        ///Sar-e Pul
        ///Sang-e Chārak
        ///Aībak
        ///Rustāq
        ///Qarqīn
        ///Qarāwul
        ///Pul-e Khumrī
        ///Paghmān
        ///Nahrīn
        ///Maymana
        ///Mehtar Lām
        ///Mazār-e Sharīf
        ///Lashkar Gāh
        ///Kushk
        ///Kunduz
        ///Khōst
        ///Khulm
        ///Khāsh
        ///Khanabad
        ///Karukh
        ///Kandahār
        ///Kabul
        ///Jalālābād
        ///Jabal os Saraj
        ///Herāt
        ///Ghormach
        ///Ghazni
        ///Gereshk
        ///Gard [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProvincesReal {
            get {
                return ResourceManager.GetString("ProvincesReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap testimage {
            get {
                object obj = ResourceManager.GetObject("testimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WorldGen {
            get {
                object obj = ResourceManager.GetObject("WorldGen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
