//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exp2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arcade_alternative {
            get {
                object obj = ResourceManager.GetObject("arcade_alternative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ArcadeAlternate {
            get {
                object obj = ResourceManager.GetObject("ArcadeAlternate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaren
        ///Aarika
        ///Abagael
        ///Abagail
        ///Abbe
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abby
        ///Abbye
        ///Abigael
        ///Abigail
        ///Abigale
        ///Abra
        ///Ada
        ///Adah
        ///Adaline
        ///Adan
        ///Adara
        ///Adda
        ///Addi
        ///Addia
        ///Addie
        ///Addy
        ///Adel
        ///Adela
        ///Adelaida
        ///Adelaide
        ///Adele
        ///Adelheid
        ///Adelice
        ///Adelina
        ///Adelind
        ///Adeline
        ///Adella
        ///Adelle
        ///Adena
        ///Adey
        ///Adi
        ///Adiana
        ///Adina
        ///Adora
        ///Adore
        ///Adoree
        ///Adorne
        ///Adrea
        ///Adria
        ///Adriaens
        ///Adrian
        ///Adriana
        ///Adriane
        ///Adrianna
        ///Adrianne
        ///Adriena
        ///Adrienne
        ///Aeriel
        ///Aeriela
        ///Aeriell
        ///Afton
        ///Ag
        ///Agace
        ///Agata
        ///Agatha
        ///Agathe
        ///Aggi
        ///Aggie
        ///Aggy
        ///Ag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirstNameReal {
            get {
                return ResourceManager.GetString("FirstNameReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap font_map_arcade_alternative {
            get {
                object obj = ResourceManager.GetObject("font_map_arcade_alternative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap font_map_unicode_arcade_alternative {
            get {
                object obj = ResourceManager.GetObject("font_map_unicode_arcade_alternative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon MainMenu {
            get {
                object obj = ResourceManager.GetObject("MainMenu", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to les Escaldes
        ///Andorra la Vella
        ///Umm al Qaywayn
        ///Ras al-Khaimah
        ///Khawr Fakkān
        ///Dubai
        ///Dibba Al-Fujairah
        ///Dibba Al-Hisn
        ///Sharjah
        ///Ar Ruways
        ///Al Fujayrah
        ///Al Ain
        ///Ajman
        ///Adh Dhayd
        ///Abu Dhabi
        ///Zaranj
        ///Taloqan
        ///Shīnḏanḏ
        ///Shibirghān
        ///Shahrak
        ///Sar-e Pul
        ///Sang-e Chārak
        ///Aībak
        ///Rustāq
        ///Qarqīn
        ///Qarāwul
        ///Pul-e Khumrī
        ///Paghmān
        ///Nahrīn
        ///Maymana
        ///Mehtar Lām
        ///Mazār-e Sharīf
        ///Lashkar Gāh
        ///Kushk
        ///Kunduz
        ///Khōst
        ///Khulm
        ///Khāsh
        ///Khanabad
        ///Karukh
        ///Kandahār
        ///Kabul
        ///Jalālābād
        ///Jabal os Saraj
        ///Herāt
        ///Ghormach
        ///Ghazni
        ///Gereshk
        ///Gard [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProvincesReal {
            get {
                return ResourceManager.GetString("ProvincesReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Wicca%244%66%241%~
        ///$Catholic%255%244%91%~
        ///$Protestant%79%96%249%~
        ///$Orthodox%173%29%111%~
        ///$Miaphysite%206%53%97%~
        ///$Judaism%199%228%234%~
        ///$Sunni%22%229%47%~
        ///$Shia%21%94%30%~
        ///$Buddhist%94%59%21%~
        ///$Shinto%188%37%0%~
        ///$Taoist%147%139%137%~
        ///$Hindu%128%204%42%~
        ///$Sikh%204%166%42%~
        ///$Celtic%133%237%30%~
        ///$Jainism%112%6%3%~
        ///$Zoroastrian%3%86%112%~
        ///$Confucian%242%155%192%~
        ///$Germanic%193%189%191%~
        ///$Slavic%70%122%3%~
        ///$Tengri%29%199%27%~
        ///$Docetist%66%53%130%~.
        /// </summary>
        public static string ReligionsReal {
            get {
                return ResourceManager.GetString("ReligionsReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaban
        ///Aabid
        ///Aabriella
        ///Aadam
        ///Aadan
        ///Aadarsh
        ///Aaden
        ///Aadesh
        ///Aadhav
        ///Aadhya
        ///Aadi
        ///Aadil
        ///Aadin
        ///Aadison
        ///Aadit
        ///Aadith
        ///Aaditya
        ///Aadon
        ///Aadya
        ///Aadyn
        ///Aafreen
        ///Aage
        ///Aagot
        ///Aahan
        ///Aahana
        ///Aahil
        ///Aahliyah
        ///Aahna
        ///Aahron
        ///Aaidan
        ///Aaiden
        ///Aaila
        ///Aailiyah
        ///Aailyah
        ///Aaira
        ///Aairah
        ///Aaisha
        ///Aaishah
        ///Aaiyana
        ///Aaiza
        ///Aaja
        ///Aajah
        ///Aajaylah
        ///Aajon
        ///Aakanksha
        ///Aakarsh
        ///Aakash
        ///Aakeem
        ///Aakilah
        ///Aakira
        ///Aakiyah
        ///Aakriti
        ///Aala
        ///Aalaiyah
        ///Aalana
        ///Aalanah
        ///Aalani
        ///Aalap
        ///Aalaya
        ///Aalayah
        ///Aalayjah
        ///Aalayna
        ///Aalaysha
        ///Aalay [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SurnamesReal {
            get {
                return ResourceManager.GetString("SurnamesReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap testimage {
            get {
                object obj = ResourceManager.GetObject("testimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon WorldGen {
            get {
                object obj = ResourceManager.GetObject("WorldGen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
